url: https://dlorenzolaguno17.github.io
baseurl: /Portfolio/

# Site settings
title: Daniel Lorenzo  |  Game Developer
email: dlorenzolaguno17@gmail.com
description: "Welcome to Daniel Lorenzo's personal webpage!"
date: "2022"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/DLorenzoLaguno17
  - title: linkedin
    url: https://www.linkedin.com/in/daniel-lorenzo-laguno-a2ab35180/
  - title: instagram
    url: https://www.instagram.com/dlorenzolaguno17/

# Postal address (add as many lines as necessary)
address:
  - line: Madrid, Community of Madrid 28014

# Build settings
markdown: kramdown
permalink: pretty