url: https://dlorenzolaguno17.github.io
baseurl: /Portfolio/

# Site settings
title: Daniel Lorenzo Laguno
email: dlorenzolaguno17@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
posts: 7

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: github
    url: http://github.com/jekyll
  - title: linkedin
    url: https://www.linkedin.com/in/daniel-lorenzo-laguno-a2ab35180/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty